# Generated by Django 3.0.8 on 2020-08-19 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionCat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('catName', models.CharField(max_length=25)),
                ('catDesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StoriesCat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('catName', models.CharField(max_length=25)),
                ('catDesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StoriesThreads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('head', models.TextField()),
                ('body', models.TextField()),
                ('conclusion', models.TextField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iReads.StoriesCat')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionThreads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('head', models.TextField()),
                ('body', models.TextField()),
                ('conclusion', models.TextField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iReads.DiscussionCat')),
            ],
        ),
    ]
