# Generated by Django 3.0.8 on 2020-08-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iReads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionthreads',
            name='author',
            field=models.CharField(default='skrb7f16', max_length=100),
        ),
        migrations.AddField(
            model_name='storiesthreads',
            name='author',
            field=models.CharField(default='skrb7f16', max_length=100),
        ),
    ]
